#!/usr/bin/env python3
# _gen_autorun_table.py -- generate the P6_GHZ_AUTORUN scripted-input hazard
# table (tools/_portspike/_p6/p6_autorun_table.h) FROM THE SCENE MANIFEST
# (extracted/Data/Stages/GHZ/Scene1.bin via tools/_ghz1_obstacle_map.py).
# Data-driven per the signpost-campaign mandate: jump waypoints come from the
# authored obstacle coordinates, not trial-and-error. Diagnostic flavor only
# (the header is included solely under -DP6_GHZ_AUTORUN).
#
# Runtime contract (InputDevice_Saturn.cpp autorun block):
#   hold A while player.x in [h.x - LEAD, h.x - GAP] and (h.y - player.y) in
#   [-JUMP_DY_UP, JUMP_DY_DOWN] -- one press edge per window, sustained hold
#   for full jump height. Overrides are raw (x0,x1,y0,y1,buttons) boxes for
#   live-iteration fixes (buttons: bit10=A jump, bit15=SUPPRESS-RIGHT,
#   bit13=DOWN, bit12=UP -- matching P6_PAD_* in InputDevice_Saturn.cpp).
import json, subprocess, sys
from pathlib import Path

HAZ = {"Motobug", "Crabmeat", "Batbrain", "Newtron", "Spikes", "SpikeLog"}

rows = json.loads(subprocess.check_output(
    [sys.executable, "tools/_ghz1_obstacle_map.py", "--json"]).decode())

pts = [(r["x"], r["y"]) for r in rows if r["cls"] in HAZ]
# Chopper (run-1 iteration, 2026-07-10): choppers sit in the water below each
# bridge (authored y = bridge y + 216: (1184,1120) vs bridge (1184,904);
# (1180,1916) vs bridge (1184,1736)) and leap up THROUGH the planks to deck
# height. The runtime dy filter compares against the player's running height,
# so register the hazard at the LEAP APEX (authored y - 216 = the deck) --
# the player then jumps just before the chopper column while crossing.
pts += [(r["x"], r["y"] - 216) for r in rows if r["cls"] == "Chopper"]
pts.sort()

# ---- live-iteration overrides (x0, x1, y0, y1, buttons) --------------------
# buttons bit meanings mirror P6_PAD_*: A=1<<10 (jump), RIGHT-SUPPRESS uses
# 1<<15 (consumed by the autorun block as "do not force RIGHT here").
# Empty until live iteration finds a spot the generic hazard-jump rule misses;
# each addition must cite the measured stall/death (x, y, cause) from the live
# position trace.
OVERRIDES = []

hdr = Path("tools/_portspike/_p6/p6_autorun_table.h")
lines = []
lines.append("/* AUTO-GENERATED by tools/_gen_autorun_table.py -- DO NOT HAND-EDIT.")
lines.append(" * GHZ1 hazard waypoints from extracted/Data/Stages/GHZ/Scene1.bin")
lines.append(" * (Scene.cpp:558-780 walk). Diagnostic P6_GHZ_AUTORUN flavor only. */")
lines.append("#ifndef P6_AUTORUN_TABLE_H")
lines.append("#define P6_AUTORUN_TABLE_H")
lines.append("typedef struct { unsigned short x, y; } P6HazardPt;")
lines.append("static const P6HazardPt p6_autorun_hazards[] = {")
for x, y in pts:
    lines.append("    { %5d, %5d }," % (x, y))
lines.append("};")
lines.append("enum { P6_AUTORUN_NHAZ = sizeof(p6_autorun_hazards) / sizeof(p6_autorun_hazards[0]) };")
lines.append("typedef struct { unsigned short x0, x1, y0, y1, buttons; } P6AutorunOverride;")
lines.append("static const P6AutorunOverride p6_autorun_overrides[] = {")
for x0, x1, y0, y1, b in OVERRIDES:
    lines.append("    { %5d, %5d, %5d, %5d, 0x%04x }," % (x0, x1, y0, y1, b))
lines.append("    { 0, 0, 0, 0, 0 }, /* terminator (keeps the array non-empty) */")
lines.append("};")
lines.append("enum { P6_AUTORUN_NOVR = sizeof(p6_autorun_overrides) / sizeof(p6_autorun_overrides[0]) - 1 };")
lines.append("#endif")
hdr.write_text("\n".join(lines) + "\n")
print("wrote %s: %d hazards, %d overrides" % (hdr, len(pts), len(OVERRIDES)))
