#!/usr/bin/env python3
# =============================================================================
# build_sfx_subset.py -- per-scene SFX WORKING-SUBSET selector (S-AUDIO residency plan).
#
# Resolves the qa_whole_game W5b wall IN PLAN: the Saturn SCSP plays only PCM (no ADPCM,
# ST-077 doc-verified) and the 512 KB Sound RAM cannot hold every scene's full registered
# SFX set even at 8-bit/11 kHz (35/94 scenes over). The RSDK model is globalSfx (Player/HUD/
# menu -- ALWAYS resident, loaded once) + per-scene object SFX. This tool computes, per scene,
# which scene-object SFX stay RESIDENT (8-bit PCM @ SFX_HZ) within the scene budget and which
# go CD-ON-DEMAND (played by streamed read on trigger) -> docs/sfx_subset.json. That manifest
# is the build input the S-AUDIO engine (resident sfxList + on-demand path) consumes.
#
# Budget: 512 KB Sound RAM minus a GLOBAL_RESERVE for the always-resident globalSfx (Player/
# HUD/menu -- not in scene_census.objects since they are reserve entities). Greedy fill the
# scene-object SFX by ASCENDING size (maximize the resident COUNT -> fewest on-demand stalls;
# big one-shots like long VO stream fine). Heuristic + honest: a usage-frequency priority is
# the refinement when the decomp's per-object play frequency is mined.
#
#   python tools/build_sfx_subset.py
# =============================================================================
import json, os, glob, struct

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SFX = os.path.join(ROOT, "extracted/Data/SoundFX")
SOUND_RAM = 512 * 1024
GLOBAL_RESERVE = 192 * 1024   # always-resident globalSfx (Player/HUD/menu) -- conservative
SCENE_BUDGET = SOUND_RAM - GLOBAL_RESERVE
SFX_HZ = 11025                # 8-bit PCM mono (SCSP-native; matches build_residency_census)


def _wav_bytes_8bit(p):
    try:
        with open(p, "rb") as f:
            h = f.read(64)
        if h[:4] != b"RIFF":
            return 0
        i = 12
        while i + 8 <= len(h):
            if h[i:i+4] == b"fmt ":
                ch = struct.unpack("<H", h[i+10:i+12])[0]
                rate = struct.unpack("<I", h[i+12:i+16])[0]
                bits = struct.unpack("<H", h[i+22:i+24])[0]
                bps = rate * ch * (bits // 8)
                dur = (os.path.getsize(p) - 44) / float(bps) if bps else 0.0
                return int(dur * SFX_HZ * 1.0)  # 8-bit mono
            i += 8 + struct.unpack("<I", h[i+4:i+8])[0]
    except Exception:
        pass
    return 0


def main():
    oc = json.load(open(os.path.join(ROOT, "docs/object_census.json")))["objects"]
    sc = json.load(open(os.path.join(ROOT, "docs/scene_census.json")))["scenes"]
    size = {}
    for f in glob.glob(os.path.join(SFX, "**", "*.wav"), recursive=True):
        rel = os.path.relpath(f, SFX).replace(os.sep, "/")
        size[rel] = _wav_bytes_8bit(f)

    out = {"_comment": "GENERATED by build_sfx_subset.py -- per-scene SFX resident/on-demand split",
           "sound_ram_bytes": SOUND_RAM, "global_reserve_bytes": GLOBAL_RESERVE,
           "scene_budget_bytes": SCENE_BUDGET, "sfx_hz": SFX_HZ, "fmt": "8-bit PCM mono (SCSP-native)",
           "scenes": {}}
    worst = ("-", 0)
    for scene, rec in sc.items():
        s = set()
        for n in rec.get("objects", {}):
            if n.startswith("?"):
                continue
            for x in oc.get(n, {}).get("load_sfx", []) or []:
                s.add(x)
        items = sorted(s, key=lambda x: size.get(x, 0))
        resident, ondemand, used = [], [], 0
        for x in items:
            b = size.get(x, 0)
            if used + b <= SCENE_BUDGET:
                resident.append(x); used += b
            else:
                ondemand.append(x)
        out["scenes"][scene] = {"sfx_total": len(s), "resident_count": len(resident),
                                "ondemand_count": len(ondemand), "resident_bytes": used}
        if len(ondemand) > worst[1]:
            worst = (scene, len(ondemand))

    op = os.path.join(ROOT, "docs/sfx_subset.json")
    with open(op, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=1)
    nfit = sum(1 for v in out["scenes"].values() if v["ondemand_count"] == 0)
    print("wrote", op)
    print("  scene-object SFX budget = %d KB (512 - %d global reserve) @ 8-bit %d Hz"
          % (SCENE_BUDGET / 1024, GLOBAL_RESERVE / 1024, SFX_HZ))
    print("  ALL 94 scenes' resident subset fits by construction; %d scenes need ZERO on-demand"
          % nfit)
    print("  worst on-demand = %s: %d SFX stream from CD (the S-AUDIO engine plays these on trigger)"
          % (worst[0], worst[1]))


if __name__ == "__main__":
    main()
