#!/usr/bin/env python3
# =============================================================================
# build_strings_census.py -- WHOLE-GAME text/localization (DATASET_STR) residency census.
#
# Closes the "asset class I did not name" gap (user 2026-06-19): the RSDK engine has FIVE
# storage pools (Storage.hpp StorageDataSets: DATASET_STG/MUS/SFX/STR/TMP). The qa_whole_game
# walls cover STG (sprites W3 + anim W6), MUS (W5a BGM), SFX (W5b), video (W7), entities
# (W1/W2), code (W4) -- but DATASET_STR (text/localization) was UNTRACKED. extracted/Data/
# Strings is a real top-level asset root: 9 per-language UTF-16 tables + Credits.txt.
#
# MEASURED model (rsdkv5-src .../Storage/Text.cpp:411 LoadStringList + AllocateStorage(...,
# sizeof(uint16)*size, DATASET_STR): the engine loads ONE active language at a time
# (Localization_LoadStrings, tools/_decomp_raw/...Localization.c), NOT all 9 resident. The
# source StringsXX.txt are ALREADY UTF-16LE (2 B/char), so the resident uint16 table size ~=
# the source file size. Resident cost = the single largest active language. Credits.txt is a
# separate Credits-scene asset (loaded only there). -> docs/strings_census.json.
#
#   python tools/build_strings_census.py
# =============================================================================
import json, os, glob

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
STR = os.path.join(ROOT, "extracted/Data/Strings")


def main():
    files = {}
    for f in sorted(glob.glob(os.path.join(STR, "*.txt"))):
        files[os.path.basename(f)] = os.path.getsize(f)

    # per-language tables = StringsXX.txt (UTF-16 source -> resident uint16 ~= source bytes).
    langs = {k: v for k, v in files.items() if k.lower().startswith("strings")}
    credits = files.get("Credits.txt", 0)
    worst_lang = max(langs.items(), key=lambda kv: kv[1]) if langs else ("-", 0)
    all_resident = sum(langs.values())  # the WRONG way (all 9 loaded) -- the rule forbids this

    out = {
        "_comment": "GENERATED by build_strings_census.py -- DATASET_STR (text/localization) residency",
        "pool": "DATASET_STR", "fmt": "UTF-16 (uint16/char); resident table ~= source bytes",
        "language_count": len(langs),
        "languages_bytes": langs,
        "credits_bytes": credits,
        "active_lang_resident_bytes": worst_lang[1],   # ONE active language (the engine model)
        "active_lang_worst": worst_lang[0],
        "all_langs_resident_bytes": all_resident,       # the anti-pattern cost (do NOT load all 9)
        "rule": ("load ONLY the active language's table (Localization_LoadStrings) -> "
                 "~%d B resident, trivially fits any pool; loading all 9 (%d B) is the anti-pattern. "
                 "Credits.txt (%d B) is a Credits-scene-only asset, not resident in gameplay."
                 % (worst_lang[1], all_resident, credits)),
    }
    op = os.path.join(ROOT, "docs/strings_census.json")
    with open(op, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=1)
    print("wrote", op)
    print("  DATASET_STR: %d languages; ACTIVE-language resident = %s %d B (worst of the 9)"
          % (len(langs), worst_lang[0], worst_lang[1]))
    print("  rule: active-language-only resident (~6 KB) -- NOT all 9 (%d B). Credits.txt = %d B (scene-only)."
          % (all_resident, credits))


if __name__ == "__main__":
    main()
