#!/usr/bin/env python3
# =============================================================================
# build_audio_census.py -- WHOLE-GAME audio memory budget census (BGM + SFX).
#
# Closes the WHOLE_GAME_MASSPORT_PLAN.md s9 gap "whole-game AUDIO has no plan": the
# 58 BGM tracks (CD-DA, share the disc with the 183 MB data pack) + the per-zone SFX
# banks (PCM, must be resident in the 512 KB SCSP Sound RAM). MEASURED from the
# extracted assets -> docs/audio_census.json, which tools/qa_whole_game.py W5 reads
# (so the constant-review gate covers the AUDIO asset class without needing the
# large gitignored extracted/ tree present).
#
# BGM: CD-DA size estimated from OGG bytes / OGG_BPS (calibrated against the measured
#   cd_audio/track02.wav = Green Hill Zone Act 1). A 74-min CD = 333,000 sectors; the
#   data pack costs data_bytes/2048 sectors, each CD-DA second costs 75 sectors.
# SFX: per-zone resident working set = Stage(always) + Global(always) + the zone bank,
#   RAW WAV bytes + a Saturn-ADPCM estimate (~3.5:1) vs the 512 KB Sound RAM.
#
#   python tools/build_audio_census.py
# =============================================================================
import json, os, glob

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
MUSIC = os.path.join(ROOT, "extracted/Data/Music")
SFX = os.path.join(ROOT, "extracted/Data/SoundFX")
OGG_BPS = 24000          # ~192 kbps OGG; calibrated vs track02.wav (Green Hill Zone Act1)
CDDA_BPS = 176400        # 16-bit 44.1 kHz stereo
CD74_SECTORS = 333000    # 74 min * 60 * 75
DATA_SECTOR = 2048       # Mode-1 data sector payload
SOUND_RAM = 512 * 1024   # SCSP Sound RAM
ADPCM_RATIO = 3.5        # Saturn ADPCM compression (WAV -> ADPCM), conservative


def _du(path):
    t = 0
    for dp, _, fs in os.walk(path):
        for f in fs:
            try:
                t += os.path.getsize(os.path.join(dp, f))
            except OSError:
                pass
    return t


def main():
    out = {"_comment": "GENERATED by build_audio_census.py -- whole-game audio memory budget",
           "cd74_sectors": CD74_SECTORS, "sound_ram_bytes": SOUND_RAM,
           "ogg_bps_est": OGG_BPS, "adpcm_ratio": ADPCM_RATIO}

    # ---- BGM (CD-DA) ----
    bgm = sorted(glob.glob(os.path.join(MUSIC, "*.ogg")))
    ogg_tot = sum(os.path.getsize(f) for f in bgm)
    dur_s = ogg_tot / float(OGG_BPS) if OGG_BPS else 0.0
    cdda_sectors = int(dur_s * 75)
    data_pack = 0
    for p in ("cd/DATA.RSDK", "game.iso"):
        fp = os.path.join(ROOT, p)
        if os.path.exists(fp):
            data_pack = os.path.getsize(fp); break
    data_sectors = (data_pack + DATA_SECTOR - 1) // DATA_SECTOR
    out["bgm"] = {
        "track_count": len(bgm), "ogg_total_bytes": ogg_tot,
        "est_duration_min": round(dur_s / 60.0, 1),
        "est_cdda_sectors": cdda_sectors,
        "data_pack_bytes": data_pack, "data_sectors": data_sectors,
        "total_sectors": cdda_sectors + data_sectors,
        "fits_one_74min_cd": (cdda_sectors + data_sectors) <= CD74_SECTORS,
        "sector_headroom": CD74_SECTORS - (cdda_sectors + data_sectors),
    }

    # ---- SFX (Sound RAM) ----
    banks = {}
    if os.path.isdir(SFX):
        for d in sorted(os.listdir(SFX)):
            dp = os.path.join(SFX, d)
            if os.path.isdir(dp):
                banks[d] = _du(dp)
    always = banks.get("Stage", 0) + banks.get("Global", 0)  # always-resident gameplay SFX
    # worst per-zone resident raw working set = always + the largest single zone bank
    zone_banks = {k: v for k, v in banks.items() if k not in ("Stage", "Global")}
    worst_zone = max(zone_banks.items(), key=lambda kv: kv[1]) if zone_banks else ("-", 0)
    worst_raw = always + worst_zone[1]
    out["sfx"] = {
        "banks_raw_bytes": banks,
        "always_raw_bytes": always,
        "worst_zone": worst_zone[0], "worst_zone_raw_bytes": worst_zone[1],
        "worst_resident_raw_bytes": worst_raw,
        "worst_resident_adpcm_est": int(worst_raw / ADPCM_RATIO),
        "fits_sound_ram_full_bank": int(worst_raw / ADPCM_RATIO) <= SOUND_RAM,
        "note": ("full per-zone bank does NOT fit 512KB even as ADPCM -> resident set MUST be "
                 "the per-SCENE registered-SFX subset (LoadSfx + globalSfx). The per-scene SFX "
                 "manifest is the next research gate (qa_zone_sfx) -- WHOLE_GAME_MASSPORT_PLAN s9."),
    }

    op = os.path.join(ROOT, "docs/audio_census.json")
    with open(op, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=1)
    print("wrote", op)
    print("  BGM: %d tracks, ~%.1f min CD-DA, total %d/%d sectors -> fits one 74min CD: %s (headroom %d)"
          % (out["bgm"]["track_count"], out["bgm"]["est_duration_min"], out["bgm"]["total_sectors"],
             CD74_SECTORS, out["bgm"]["fits_one_74min_cd"], out["bgm"]["sector_headroom"]))
    print("  SFX: worst resident = always(%d) + %s(%d) = %d raw / %.1f MB ADPCM est vs 512KB -> fits: %s"
          % (always, worst_zone[0], worst_zone[1], worst_raw,
             out["sfx"]["worst_resident_adpcm_est"] / 1e6, out["sfx"]["fits_sound_ram_full_bank"]))


if __name__ == "__main__":
    main()
