#!/usr/bin/env python3
# =============================================================================
# build_residency_census.py -- WHOLE-GAME per-scene RESIDENCY budget (SFX + anim + video).
#
# Resolves the W5b SFX-manifest TODO + the animation (W6) + video (W7) asset classes
# of tools/qa_whole_game.py, from the ALREADY-DONE research:
#   * object_census.objects[name].load_sfx / load_anims  (per-object asset manifest)
#   * object_census.zones[zone].anim_bins_loaded          (per-zone anim .bin set)
#   * scene_census.scenes[scene].objects                  (per-scene object roster; ~97% name-resolved)
#   * the extracted asset file sizes                      (Sprites/*.bin, SoundFX/*.wav, Video/*.ogv)
# -> docs/residency_census.json. Data-driven; no engine build. The 2-3 unmapped-hash
# scene objects per scene are reported as a coverage gap (use build_gameconfig_hash_table
# to close it later) -- they do NOT silently inflate a budget.
#
# SFX (Sound RAM 512 KB, per-SCENE working set): each scene loads the UNION of its objects'
#   load_sfx PCM .wav; on Saturn that is ADPCM (~3.5:1). The resident set must fit 512 KB.
# ANIM (DATASET_STG pool, per-ZONE): the .bin set source bytes. CAVEAT: the pool holds
#   DECODED frames, so .bin (compressed) is a LOWER bound -- a decoded-frame census is the
#   precise W6 (flagged). Reported as the source-size dashboard.
# VIDEO (intro Cinepak FILM, CD-streamed at boot): Mania.ogv source size + the disc-space
#   note (the FILM rides the data track; fits within the W5a CD headroom).
#
#   python tools/build_residency_census.py
# =============================================================================
import json, os, glob

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SOUND_RAM = 512 * 1024
ADPCM_RATIO = 3.5


def _index(root, ext):
    # map 'Zone/Name.ext' -> bytes, for every file under root (case-insensitive ext)
    idx = {}
    for f in glob.glob(os.path.join(root, "**", "*" + ext), recursive=True):
        rel = os.path.relpath(f, root).replace("\\", "/")
        idx[rel] = os.path.getsize(f)
    return idx


def main():
    oc = json.load(open(os.path.join(ROOT, "docs/object_census.json")))
    sc = json.load(open(os.path.join(ROOT, "docs/scene_census.json")))
    objs = oc["objects"]
    zones = oc.get("zones", {})

    wav = _index(os.path.join(ROOT, "extracted/Data/SoundFX"), ".wav")
    bins = _index(os.path.join(ROOT, "extracted/Data/Sprites"), ".bin")

    out = {"_comment": "GENERATED by build_residency_census.py -- per-scene SFX + per-zone anim + video",
           "sound_ram_bytes": SOUND_RAM, "adpcm_ratio": ADPCM_RATIO, "scenes": {}, "zones": {}}

    # ---- per-SCENE SFX working set (W5b) ----
    for scene, rec in sc["scenes"].items():
        names = [k for k in rec.get("objects", {}) if not k.startswith("?")]
        unmapped = len(rec.get("objects", {})) - len(names)
        sfx_set = set()
        for n in names:
            for s in objs.get(n, {}).get("load_sfx", []) or []:
                sfx_set.add(s)
        raw = sum(wav.get(s, 0) for s in sfx_set)
        out["scenes"][scene] = {
            "objects_named": len(names), "objects_unmapped": unmapped,
            "sfx_count": len(sfx_set), "sfx_raw_bytes": raw,
            "sfx_adpcm_est": int(raw / ADPCM_RATIO),
            "sfx_fits_sound_ram": int(raw / ADPCM_RATIO) <= SOUND_RAM,
        }

    # ---- per-ZONE anim .bin source size (W6 dashboard; decoded-pool is the precise next gate) ----
    for zone, zrec in zones.items():
        ab = zrec.get("anim_bins_loaded", []) or []
        raw = sum(bins.get(b, 0) for b in ab)
        out["zones"][zone] = {"anim_bin_count": len(ab), "anim_bin_source_bytes": raw}

    # ---- VIDEO (intro Cinepak FILM) ----
    ogv = os.path.join(ROOT, "extracted/Data/Video/Mania.ogv")
    cpk = os.path.join(ROOT, "cd/INTRO.CPK")
    out["video"] = {
        "source_ogv_bytes": os.path.getsize(ogv) if os.path.exists(ogv) else 0,
        "current_saturn_cpk_bytes": os.path.getsize(cpk) if os.path.exists(cpk) else 0,
        "note": ("intro plays at BOOT (full machine, not gameplay-perf-critical). The Cinepak FILM "
                 "rides the DATA track -> costs disc sectors (fits within the W5a ~21.8K-sector / 4.8min "
                 "CD headroom for a low-res Saturn FILM). Decode = SBL Cinepak (proven). The 82KB "
                 "INTRO.CPK is a stub; the full FILM build is the port step."),
    }

    op = os.path.join(ROOT, "docs/residency_census.json")
    with open(op, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=1)

    over = [(v["sfx_adpcm_est"], k) for k, v in out["scenes"].items() if not v["sfx_fits_sound_ram"]]
    worst = max(out["scenes"].items(), key=lambda kv: kv[1]["sfx_adpcm_est"]) if out["scenes"] else ("-", {})
    zworst = max(out["zones"].items(), key=lambda kv: kv[1]["anim_bin_source_bytes"]) if out["zones"] else ("-", {})
    print("wrote", op)
    print("  SFX per-scene worst = %s: %.0f KB ADPCM est (vs 512 KB)  -- %d/%d scenes OVER"
          % (worst[0], worst[1].get("sfx_adpcm_est", 0) / 1024.0, len(over), len(out["scenes"])))
    print("  ANIM per-zone worst = %s: %.0f KB .bin source (decoded pool is the precise gate)"
          % (zworst[0], zworst[1].get("anim_bin_source_bytes", 0) / 1024.0))
    print("  VIDEO: Mania.ogv = %.1f MB source -> low-res Cinepak FILM on the data track (boot)"
          % (out["video"]["source_ogv_bytes"] / 1e6))


if __name__ == "__main__":
    main()
