#!/usr/bin/env python3
# =============================================================================
# build_scene_census.py -- authoritative per-SCENE placed-object census.
#
# WHY: the object census (build_object_census.py) scoped to a zone's StageConfig
# object table, which is the WHOLE zone (Act1 + Act2 + boss + cutscenes + all-
# character support) -> the GHZ closure over-counted to 52 sheets. The REAL
# "what must drop in for GHZ Act 1" is the set of objects actually PLACED in
# Scene1.bin. dump_all_scenes.py only heuristically scanned for name-ish strings
# (garbled names_seen). This parses Scene*.bin PROPERLY.
#
# Scene.bin format (verbatim from rsdkv5-src Scene.cpp:324-597; entity walk
# proven in extract_ghz_spawn.py): 'SCN\0' + 0x10 hdr + editor-meta string +
# layerCount + layers (name, type, 4xu16 dims, scrollInfo[6 each], 2x zlib
# blobs) + objectCount + objects { 16-B md5(className) hash, varCount,
# (varCount-1)x{16-B attr-hash, u8 type}, entityCount, entities{slot u16, x
# i32, y i32, attr values by type} }. Object name = md5(name) match (ASCII,
# case-sensitive; extract_ghz_spawn.py:93). Coords are Q16.16 -> px = v>>16.
#
# Emits docs/scene_census.json: per zone/scene the placed objects with instance
# count + coords. Re-runnable; deterministic. No guessing.
# =============================================================================
import hashlib
import json
import os
import re
import struct
import sys
import zlib

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
STAGES = os.path.join(ROOT, "extracted", "Data", "Stages")
RAW = os.path.join(ROOT, "tools", "_decomp_raw")
OUT_JSON = os.path.join(ROOT, "docs", "scene_census.json")

# Build md5(name)->name over every decomp object name + a few engine pseudo-
# objects. Case-sensitive ASCII (extract_ghz_spawn.py:93 uses md5(b"Player")).
def build_hash_table():
    names = set()
    for fn in os.listdir(RAW):
        m = re.match(r'SonicMania_Objects_[A-Za-z0-9]+_(.+)\.c$', fn)
        if m:
            names.add(m.group(1))
    # engine default classes present in scenes but not object TUs
    names.update(["Blank", "TestObject", "DefaultObject", "DevOutput", "Player"])
    return {hashlib.md5(n.encode("ascii")).digest(): n for n in names}

ATTR_SIZE = {  # RSDKv5 editable-var type -> reader (extract_ghz_spawn.py:113-127)
    0: ("u8", 1), 1: ("u16", 2), 2: ("u32", 4), 3: ("i8", 1), 4: ("i16", 2),
    5: ("i32", 4), 6: ("u32", 4), 7: ("u32", 4), 9: ("vec2", 8), 11: ("u32", 4),
}

class R:
    def __init__(self, b): self.d, self.p = b, 0
    def u8(self): v = self.d[self.p]; self.p += 1; return v
    def u16(self): v = struct.unpack_from("<H", self.d, self.p)[0]; self.p += 2; return v
    def u32(self): v = struct.unpack_from("<I", self.d, self.p)[0]; self.p += 4; return v
    def i32(self): v = struct.unpack_from("<i", self.d, self.p)[0]; self.p += 4; return v
    def take(self, n): v = self.d[self.p:self.p + n]; self.p += n; return v
    def s(self): n = self.u8(); return self.take(n)
    def compressed(self):
        total = self.u32(); self.u32(); clen = total - 4
        return self.take(clen)  # consume; we don't need the layout bytes here

def parse_scene(path, h2n):
    d = open(path, "rb").read()
    r = R(d)
    if d[:4] != b"SCN\x00":
        raise RuntimeError("not SCN")
    r.p = 4
    r.take(0x10)
    nl = r.u8(); r.take(nl + 1)               # editor metadata string + pad
    layer_count = r.u8()
    for _ in range(layer_count):
        r.u8(); r.s(); r.u8(); r.u8()
        r.u16(); r.u16(); r.u16(); r.u16()
        sic = r.u16()
        for _ in range(sic):
            r.take(6)
        r.compressed(); r.compressed()         # lineScroll indexes + tile layout

    placed = {}
    unmapped = []
    obj_count = r.u8()
    for _ in range(obj_count):
        nhash = r.take(16)
        name = h2n.get(nhash)
        var_count = r.u8()
        attribs = []
        for _ in range(max(0, var_count - 1)):
            ah = r.take(16); at = r.u8()
            attribs.append(at)
        entity_count = r.u16()
        coords = []
        for _ in range(entity_count):
            slot = r.u16(); x = r.i32(); y = r.i32()
            for at in attribs:
                if at == 8:                     # STRING: u16 len + len*2 (UTF16)
                    n = r.u16(); r.take(n * 2)
                elif at in ATTR_SIZE:
                    r.take(ATTR_SIZE[at][1])
                else:
                    raise RuntimeError("attr type %d" % at)
            coords.append((slot, x >> 16, y >> 16))
        key = name or ("?" + nhash.hex()[:8])
        if name is None:
            unmapped.append(nhash.hex())
        placed[key] = {"count": entity_count, "coords": coords}
    return placed, unmapped

def main():
    h2n = build_hash_table()
    out = {"_comment": "GENERATED by build_scene_census.py -- per-scene placed objects",
           "scenes": {}}
    nscenes = 0
    for folder in sorted(os.listdir(STAGES)):
        fdir = os.path.join(STAGES, folder)
        if not os.path.isdir(fdir):
            continue
        for fn in sorted(os.listdir(fdir)):
            if re.match(r'Scene.*\.bin$', fn):
                key = "%s/%s" % (folder, fn)
                try:
                    placed, unmapped = parse_scene(os.path.join(fdir, fn), h2n)
                    out["scenes"][key] = {
                        "object_count": len(placed),
                        "entity_total": sum(v["count"] for v in placed.values()),
                        "objects": {k: v["count"] for k, v in sorted(placed.items())},
                        "unmapped_hashes": unmapped,
                        "_coords": {k: v["coords"] for k, v in placed.items()},
                    }
                    nscenes += 1
                except Exception as e:
                    out["scenes"][key] = {"error": str(e)}
    json.dump(out, open(OUT_JSON, "w", encoding="utf-8"), indent=1)

    # Summary + the GHZ Act 1 placed-object list (the concrete deliverable).
    print("=" * 74)
    print("SCENE CENSUS -- %d scenes parsed across %d stage folders"
          % (nscenes, len(set(k.split('/')[0] for k in out["scenes"]))))
    print("=" * 74)
    for sk in ("GHZ/Scene1.bin", "GHZ/Scene2.bin"):
        s = out["scenes"].get(sk)
        if not s or "objects" not in s:
            print("%s: %s" % (sk, s)); continue
        print("\n%s -- %d distinct objects, %d entities placed%s:"
              % (sk, s["object_count"], s["entity_total"],
                 ("  [%d UNMAPPED hashes]" % len(s["unmapped_hashes"])) if s["unmapped_hashes"] else ""))
        for name, cnt in sorted(s["objects"].items(), key=lambda kv: -kv[1]):
            print("    %4d x %s" % (cnt, name))
    print("\nmanifest -> %s" % os.path.relpath(OUT_JSON, ROOT))
    return 0

if __name__ == "__main__":
    sys.exit(main())
